### ISSUE TITLE
pgcopydb dump schema --target not working

### ISSUE THREAD

**Issue by renegrob** [dimitri/pgcopydb#103]
Hi,
I copy-pasted  the `pgcopydb dump schema` from the manual and I get the following error:

```
sh-5.1$ pgcopydb dump schema --target /tmp/target
09:24:57 29 INFO  Running pgcopydb version 0.8-1.pgdg110+1 from "/usr/bin/pgcopydb"
09:24:57 29 ERROR Failed to parse connection string "/tmp/target": missing "=" after "/tmp/target" in connection info string
```
It seems to me that `pgcopydb` tries to parse the `--target` parameter as connection string but according to the manual it should be a directory. I'm I doing something wrong or is this a bug?

**Comment by dimitri** [comment]
Hi @renegrob ; thanks for the bug report. The docs (and command help strings) need an update, the `--target` option used to serve two purposes depending on the command, either a connection string to target Postgres instance or a target directory. I have cleaned that up recently and missed updating the help strings and docs.

Now `--target` is always the connection string to the target Postgres instance. And `--dir` is always the work directory that's being used by the command.

So please use `pgcopydb dump schema --source ... --dir /tmp/target` ; despite the docs saying otherwise. I'll go and fix them later.

**Comment by renegrob** [comment]
Oh, that's why. Thank you!
