### ISSUE TITLE
include-only-table fails if we already have the schema in the target

### ISSUE THREAD

**Issue by asarchami** [dimitri/pgcopydb#255]
When trying to use pgcopydb clone with --filter option `[include-only-table]`, I get the error that the schema already exists and fails to run pg_restore.

**Comment by dimitri** [comment]
I think this has been fixed with recent improvements to schema discovery on the target in https://github.com/dimitri/pgcopydb/pull/341. Closing this issue for triage. Please re-open with more information if needed (actual output from running the command, and a test case to reproduce the problem, both would be nice to have to be able to help).
