### ISSUE TITLE
option to exclude schemas

### ISSUE THREAD

**Issue by akhilkanjarla** [dimitri/pgcopydb#4]
Would be nice to be able to have an option to exclude or select multiple schemas from the db.

**Comment by df7cb** [comment]
I guess it would make sense to accept all switches that pg_dump and pg_restore accept, and pass them through to the respective tool.

See also #3.

**Comment by dimitri** [comment]
I am not sure that it would make sense for us to accept all the different options, ans also I would like to keep things as simple as possible. About excluding schemas and table and table data, I think we should `pg_dump` as today (it's schema-only anyway), and then filter in our own catalog queries for tables and indexes, and in the way we call into `pg_restore` to avoid creating the target objects at all when that's the instructions.

I don't like having to set a very long command line with the same `--exclude-schema` and `--schema` and `--table` multiple times each; so I'm thinking we could provide a configuration file such as:

``` ini
[exclude-schema]
foo
bar

[exclude-table]
schema.name
schema.othername

[exclude-index]
schema.indexname

[exclude-table-data]
public.bar
```

We could have support for a section named `[include-only-table]` that could have a list of qualified table names in there, and an optional `[include-only-index]` section, though then we probably want to have an either/or implementation that only accepts the include-only facility or the exclude facilities when it comes to picking which tables are taken care of. Some include/exclude options would be allowed together, I suppose, as in the following idea:

```ini
[include-only-table]
public.foo
public.bar

[exclude-index]
public.foo_gin_tsvector

[exclude-table-data]
public.bar
```

We would then grab the OID of objects on the source server and filter them out from the `pg_restore` operations thanks to using the `--use-list` mechanics, as we do today to avoid creating the indexes and constraints twice when we've done it before hand.

It seems to me to be more flexible and easier to understand compared to exposing the bare `pg_dump` and `pg_restore` options and having to deal with impossibly convoluted command lines.

**Comment by df7cb** [comment]
I had hoped that `--exclude-schema` and `--use-list` would be compatible in the sense that the list emitted by `pg_dump --exclude-schema` would just not include the schema and no extra effort would be necessary except for passing on the option

**Comment by dimitri** [comment]
I think for this very simple case it might just work. Now say you want to exclude everything in the schema except for one table, and skip one of its indexes. How do you do that? Many advanced use-cases are just the hell to implement, and I have always ended-up doing a full schema pg_dump anyway and then a selective pg_restore using hand crafted `--use-list`, and in cases, scripted `--use-list`.

In the case of `pgcopydb` we should also have support for `--exclude-table-data`, and because we only use pg_dump for the schema anyway, we have to implement this bits ourselves.

**Comment by maxstepanov** [comment]
If I want to exclude just a few tables I'd rather use a cli option than a config file.

**Comment by akhilkanjarla** [comment]
@dimitri Thanks. Config file exlcudes/includes works for my usecase where we want to exclude multiple schemas and tables from copying.

**Comment by DanRStevens** [comment]
I was also looking for a way to copy just a single schema, and to not disturb anything else in the destination database.

If renaming the schema during the copy could be supported, that would be even better, though I fear I may be wishing for a bit much. In my use case, we do staging deployments of our app, which uses a clone of the production data, but copied to a testing DB server, and then with the schema renamed based on the branch that is being worked on. Due to the possibility of multiple branches from multiple developers being deployed at once, we need to put a lock around the DB copy, since the default dump/restore keeps the destination schema name the same, and we don't want different copies to clobber each other. The rename is done after the copy completes, and before the lock is released.

Anyway, just being able to copy a single schema, in a faster way, would be great.

**Comment by dimitri** [comment]
I have now merged a PR that implements the `--filter <filename.ini>` approach with lots of flexibility. I hope it solves all the use cases mentioned here about filtering. Let me know by commenting here or opening a new issue otherwise.

About the schema renaming mentioned by @DanRStevens ; this would need parsing of all the commands in the pg_restore output, and that's not something I want to pursue at this time. As mentioned elsewhere, consider doing a copy of the schema as it is and then use ALTER SCHEMA ... RENAME TO ... instead.
