### ISSUE TITLE
Support reading logical messages from pgoutput plugin

### ISSUE THREAD

**Issue by arajkumar** [dimitri/pgcopydb#472]
Currently pgcopydb supports 2 plugins, (wal2json and test_decoding), while it should work for most of the use cases, but it lacks the flexibility offered by the pgoutput through CREATE PUBLICATION(row filtering, table, scheme selection). Additionally, pgoutput plugin known to be part of the postgres distribution, but not sure it is the same case with wal2json and test_decoding.

The idea is to create pgoutput based logical replication slot using CREATE PUBLICATION and read the slot from pgcopydb.

**Comment by dimitri** [comment]
Please see issue #387. I believe we should just add support for Logical Replication on-top of Logical Decoding. Rationale is that Logical Decoding is needed for older Postgres sources (9.5, 9.6, 10, I believe), and for Logical Replication superuser is required, which is not something that everybody can use. 

Also, I don't think it's possible to use `pgoutput` plugin with logical decoding API, without using logical replication API (which is superuser only). That's why I believe we should add support for Logical Replication then.

**Comment by arajkumar** [comment]
Sorry for the poor choice of words :) Actually, my request is not to support pgoutput, but to read logical messages from a slot which is created with `CREATE PUBLICATION`, so that the user could avail features like row filtering and table selection. Thanks, @dimitri for pointing me to the related issue. Indeed, #387 aligns well with my thought process. 

Let me close this issue.
